### ISSUE TITLE
How to fix this problem?

### ISSUE THREAD

**Issue by 126RockStar** [aliozgur/WinScp.SftpProxy#1]
How are you?

Thank you for you tool.

But I can't login my AWS sftp server.
My error is below.
Please help me.

Error: WinSCP.SessionRemoteException: Host key does not match configured key fingerprint "ssh-rsa 2048 77:a6:80:f5:d3:b3:e7:06:87:23:b9:a2:b3:0a:52:c4"!
Host key fingerprint is ssh-rsa 2048 QX1rrzDHCXFFQt+o0jyNKOHSLIUh3rGCepRYI4DJ6o4=.
Authentication failed.
   at WinSCP.SessionLogReader.Read(LogReadFlags flags)
   at WinSCP.ElementLogReader.Read(LogReadFlags flags)
   at WinSCP.SessionElementLogReader.Read(LogReadFlags flags)
   at WinSCP.CustomLogReader.TryWaitForNonEmptyElement(String localName, LogReadFlags flags)
   at WinSCP.CustomLogReader.WaitForNonEmptyElement(String localName, LogReadFlags flags)
   at WinSCP.Session.WaitForGroup()
   at WinSCP.Session.Open(SessionOptions sessionOptions)
   at TA6_Service.Jobs.UploadJob.TransferSFTP(String filepath) in E:\A_Task\2020_03_05_TA6_Australia\Project\TA6_Service\TA6_Service\Jobs\UploadJob.cs:line 53
The program '[16308] TA6_Service.exe' has exited with code -1 (0xffffffff).

**Comment by aliozgur** [comment]
Hi,
I guess your fingerprint format has a problem or not supported by WinSCP. Please refer to https://winscp.net/forum/viewtopic.php?t=23690 to learn how you can generate a valid fingerprint for WinSCP.
